# Change these first
owner: federated-research # Your GitHub organization or username, where this repository lives
repo: 5S-TES-Status # The name of this repository

sites:
  - name: New Submission API
    check: "tcp-ping"
    url: 172.167.66.153
    port: 5034
  - name: New TRE API
    check: "tcp-ping"
    url: 172.167.137.69
    port: 8072
  - name: New Funnel
    check: "tcp-ping"
    url: 172.167.109.83
    port: 80
assignees: # Users to assign downtime issues (optional)
  - AndrewThien
  - vpnu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /5S-TES-Status
  logoUrl: https://raw.githubusercontent.com/federated-research/5S-TES-Status/refs/heads/master/logo.png
  name: Five Safes TES
  favicon: https://raw.githubusercontent.com/federated-research/5S-TES-Status/refs/heads/master/logo.png
  introTitle: "5S-TES status"
  introMessage: A site to monitor the status of deployed 5S-TES stack on VMs
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
