# Change these first
owner: federated-research # Your GitHub organization or username, where this repository lives
repo: 5S-TES-Status # The name of this repository

sites:
  - name: Submission Frontend
    url: https://5s-tes.federated-research.com/
  - name: Submission Backend
    url: https://api.5s-tes.federated-research.com/swagger/index.html
  - name: Nottingham TRE 01 Frontend
    url: https://tre-01.5s-tes.federated-research.com/
  - name: Nottingham TRE 01 Backend
    url: https://api.tre-01.5s-tes.federated-research.com/swagger/index.html
assignees: # Users to assign downtime issues (optional)
  - AndrewThien
  - vpnu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.5s-tes.federated-research.com
  # baseUrl: /5S-TES-Status
  logoUrl: https://raw.githubusercontent.com/federated-research/5S-TES-Status/refs/heads/master/logo.png
  name: Five Safes TES
  favicon: https://raw.githubusercontent.com/federated-research/5S-TES-Status/refs/heads/master/logo.png
  introTitle: "5S-TES status"
  introMessage: A site to monitor the status of deployed 5S-TES stack on VMs
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
